version: '3.8'

services:
  php-apache:
    container_name: PHP_Contratos_project
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage  # Volumen compartido para acceso a storage

    ports:
      - "8181:80"
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    depends_on:
      - mysql
      - redis
      - rabbitmq
    networks:
      - contratos_default   # Red compartida

  mysql:
    container_name: mysql_contratos
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: contratos
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - contratos_default   # Red compartida

  redis:
    container_name: redis_contratos
    image: redis:alpine
    ports:
      - "6380:6380"
    networks:
      - contratos_default   # Red compartida

  rabbitmq:
    container_name: rabbitmq_contratos
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "15672:15672"  # Interfaz de administración de RabbitMQ
      - "5672:5672"     # Puerto de comunicación de RabbitMQ
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - contratos_default   # Red compartida

volumes:
  db_data:
  rabbitmq_data:

networks:
  contratos_default:
    external: true  # Usar la red externa contratos_default
