version: '3.8'

services:
  php-apache:
    container_name: PHP_Contratos_project
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "8181:80"
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    depends_on:
      - mysql
      - redis
      
  mysql:
    container_name: mysql_contratos
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: contratos
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    container_name: redis_contratos
    image: redis:alpine
    ports:
      - "6380:6380"

volumes:
  db_data:

